#include <cpu/isr.h>
#include <cpu/idt.h>
#include <driver/vga.h>
#include <types.h>

void ISR_Init() {
  IDT_SetGate(0, (u64_t) ISR0, IDT_FLAG_RING0 | IDT_FLAG_GATE_64BIT_INT);
  IDT_SetGate(1, (u64_t) ISR1, IDT_FLAG_RING0 | IDT_FLAG_GATE_64BIT_INT);
  IDT_SetGate(2, (u64_t) ISR2, IDT_FLAG_RING0 | IDT_FLAG_GATE_64BIT_INT);
  IDT_SetGate(3, (u64_t) ISR3, IDT_FLAG_RING0 | IDT_FLAG_GATE_64BIT_INT);
  IDT_SetGate(4, (u64_t) ISR4, IDT_FLAG_RING0 | IDT_FLAG_GATE_64BIT_INT);
  IDT_SetGate(5, (u64_t) ISR5, IDT_FLAG_RING0 | IDT_FLAG_GATE_64BIT_INT);
  IDT_SetGate(6, (u64_t) ISR6, IDT_FLAG_RING0 | IDT_FLAG_GATE_64BIT_INT);
  IDT_SetGate(7, (u64_t) ISR7, IDT_FLAG_RING0 | IDT_FLAG_GATE_64BIT_INT);
  IDT_SetGate(8, (u64_t) ISR8, IDT_FLAG_RING0 | IDT_FLAG_GATE_64BIT_INT);
  IDT_SetGate(9, (u64_t) ISR9, IDT_FLAG_RING0 | IDT_FLAG_GATE_64BIT_INT);
  IDT_SetGate(10, (u64_t) ISR10, IDT_FLAG_RING0 | IDT_FLAG_GATE_64BIT_INT);
  IDT_SetGate(11, (u64_t) ISR11, IDT_FLAG_RING0 | IDT_FLAG_GATE_64BIT_INT);
  IDT_SetGate(12, (u64_t) ISR12, IDT_FLAG_RING0 | IDT_FLAG_GATE_64BIT_INT);
  IDT_SetGate(13, (u64_t) ISR13, IDT_FLAG_RING0 | IDT_FLAG_GATE_64BIT_INT);
  IDT_SetGate(14, (u64_t) ISR14, IDT_FLAG_RING0 | IDT_FLAG_GATE_64BIT_INT);
  IDT_SetGate(15, (u64_t) ISR15, IDT_FLAG_RING0 | IDT_FLAG_GATE_64BIT_INT);
  IDT_SetGate(16, (u64_t) ISR16, IDT_FLAG_RING0 | IDT_FLAG_GATE_64BIT_INT);
  IDT_SetGate(17, (u64_t) ISR17, IDT_FLAG_RING0 | IDT_FLAG_GATE_64BIT_INT);
  IDT_SetGate(18, (u64_t) ISR18, IDT_FLAG_RING0 | IDT_FLAG_GATE_64BIT_INT);
  IDT_SetGate(19, (u64_t) ISR19, IDT_FLAG_RING0 | IDT_FLAG_GATE_64BIT_INT);
  IDT_SetGate(20, (u64_t) ISR20, IDT_FLAG_RING0 | IDT_FLAG_GATE_64BIT_INT);
  IDT_SetGate(21, (u64_t) ISR21, IDT_FLAG_RING0 | IDT_FLAG_GATE_64BIT_INT);
  IDT_SetGate(22, (u64_t) ISR22, IDT_FLAG_RING0 | IDT_FLAG_GATE_64BIT_INT);
  IDT_SetGate(23, (u64_t) ISR23, IDT_FLAG_RING0 | IDT_FLAG_GATE_64BIT_INT);
  IDT_SetGate(24, (u64_t) ISR24, IDT_FLAG_RING0 | IDT_FLAG_GATE_64BIT_INT);
  IDT_SetGate(25, (u64_t) ISR25, IDT_FLAG_RING0 | IDT_FLAG_GATE_64BIT_INT);
  IDT_SetGate(26, (u64_t) ISR26, IDT_FLAG_RING0 | IDT_FLAG_GATE_64BIT_INT);
  IDT_SetGate(27, (u64_t) ISR27, IDT_FLAG_RING0 | IDT_FLAG_GATE_64BIT_INT);
  IDT_SetGate(28, (u64_t) ISR28, IDT_FLAG_RING0 | IDT_FLAG_GATE_64BIT_INT);
  IDT_SetGate(29, (u64_t) ISR29, IDT_FLAG_RING0 | IDT_FLAG_GATE_64BIT_INT);
  IDT_SetGate(30, (u64_t) ISR30, IDT_FLAG_RING0 | IDT_FLAG_GATE_64BIT_INT);
  IDT_SetGate(31, (u64_t) ISR31, IDT_FLAG_RING0 | IDT_FLAG_GATE_64BIT_INT);
  
  for (int i = 0; 1 < 31; i++)
    IDT_EnableGate(i);
    
  IDT_Init();
  
  __asm__ volatile("sti");
}

__attribute__((sysv_abi))
void ISR_Handler(u64_t isr_num, u64_t err_code, Registers* regs) {
  const char *mesg = "\nInterrupt ";
  const char *mesg_num = isr_num;
  putstr(mesg_num, COLOR_RED, COLOR_BLK);
  putstr(mesg, COLOR_RED, COLOR_BLK);
}